### ISSUE TITLE
Testing question: mock GBIF API?

### ISSUE THREAD

**Issue by niconoe** [sckott/pygbif#42]
Hi,

I was considering trying to find a bit of time this year to contribute to pygbif, and in my opinion making the test suite more exhaustive would be a good way to start!

Currently, it seems pygbif test suite consumes the "real" GBIF API, which is IMHO suboptimal (fragility, some tests are difficult to implement, speed considerations, ...). I was therefore considering (in another project) to create an Mock object (or mock server) that could be consumed by pygbif and other similar projects. 

If such a project existed, would you be interested in using it to improve pygbif test suite?

**Comment by sckott** [comment]
hi @niconoe !

when I first read the subject of the issue I thought you were going to say mock tests as in https://github.com/kevin1024/vcrpy or https://github.com/sigmavirus24/betamax - so that we can basically cache real responses and then test against those - which we can do and would speed up tests

as far as a mock server, that would be useful. would it be possible though to get a matching service as close as possible so that we wouldn't run into problems where a test works against the mock server but not against real GBIF or vice versa? 

saw your email to the mailing list - Go sounds like a good choice since easy cross platform binaries -

**Comment by niconoe** [comment]
Indeed, the server has to match very closely the real GBIF infrastructure, otherwise it's creating more problems than it solve. 

I may use something similar to vcrpy during its development to have more realistic mock data, but that returned data will then be stable, i.e. like a "frozen" copy of the GBIF api. 

Currently, `pygbif` test suite test two things at the same time: the correct behavior of pygbif, but also the current status of api.gbif.org. I want to provide a tool (or a couple of tools) that decouple those two things. 

Anyway, I'll get started soon, and my first milestone would have something "good enough to run pygbif test suite".

Thanks for your input!
